image:
  repository: alessiosou/formazione_sou_k8s
  tag: "latest"
  pullPolicy: IfNotPresent

containerPort: 8000

replicas: 1

service:
  type: NodePort
  port: 80

readinessProbe:
  enabled: true
  httpGet:
    path: /
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

livenessProbe:
  enabled: true
  httpGet:
    path: /
    port: 8000
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3